export const GAME_CONFIG = {
  MAP_WIDTH: 1536,
  MAP_HEIGHT: 1024,

  PLAYER_SPEED: 130,
  PLAYER_SIZE: 64,

  DISCOVERED_RUNES: 4,
  DISCOVERED_RELICS: 3,
  DISCOVERED_SCROLLS:3,
  DISCOVERED_ARTIFACTS:3,

  INTERACTION_DISTANCE: 70,
};